apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  statefulset:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume-example-mongodb-0
        spec:
          storageClassName: manual
